### ISSUE TITLE
한국어 적용 시 띄어쓰기가 이상해지는 점

### ISSUE THREAD

**Issue by JiaeK** [green-labs/ko.rescript#3]
![한글 띄워쓰기 문제](https://user-images.githubusercontent.com/78751231/214503594-a1a393e1-249b-4c1e-98bc-b10ba2d93fda.png)

위의 참고 사진과 같이, 한국어 적용 시, (특히 메인 페이지 같은 곳에서) 띄어쓰기가 이상해지는 경우가 있어, 읽을 때 불편함을 느낄 수 있다고 봅니다. 
단문의 경우 `<br/>`을 이용해 어느 정도 띄어쓰기를 할 수 있는데 ([예시](https://github.com/green-labs/ko.rescript/blob/25374e3b74ab595dbce530e6c21a1663362d81ff/src/layouts/LandingPageLayout.res#L7-L11)), 
[장문의 경우](https://github.com/green-labs/ko.rescript/blob/25374e3b74ab595dbce530e6c21a1663362d81ff/src/layouts/LandingPageLayout.res#L377-L379), 예를 들어 `<br/>`을 쓰면, 화면의 크기에 따라 문장의 배열이 바뀌므로, 어느 화면 크기에 맞춰야 할지 모르게 됩니다. 
한국어로 표기할 때, Responsive 하면서 띄어쓰기도 적용되는 방법이 있었으면 좋겠습니다.

**Comment by namenu** [comment]
아 이거 keep-all 을 넣어야 해요 ㅋㅋ
