### ISSUE TITLE
introduction.md에서의 각주

### ISSUE THREAD

**Issue by JiaeK** [green-labs/ko.rescript#7]
예전 번역본을 참고하여 [introduction.md](https://github.com/green-labs/ko.rescript/blob/main/pages/docs-ko/manual/latest/introduction.mdx)에서의 [각주](https://github.com/green-labs/ko.rescript/blob/main/pages/docs-ko/manual/latest/introduction.mdx#:~:text=%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4.%20%EC%9D%B4%EB%A5%B8%EB%B0%94%2C%20%22%EC%82%AC%EC%9A%B4%EB%93%9C%22-,1,-%ED%95%9C%2C%20%ED%95%AD%EC%83%81%20%EC%A0%95%ED%99%95%ED%95%9C)를 옮겨왔습니다. 새 번역본에서도 각주를 계속해서 사용할 것인지에 확인 부탁 드립니다.

**Comment by namenu** [comment]
예전에도 각주고 있었던 것 같은데.. 없어도 되겠습니다.

**Comment by JiaeK** [comment]
Edit in https://github.com/green-labs/ko.rescript/commit/ba8f5ae192d8e83792e9e0c37a3f38b2b87961ae
